### ISSUE TITLE
Topics for development

### ISSUE THREAD

**Issue by emitanaka** [numbats/learnr#2]
- [x] Getting started with R and RStudio IDE (@DanyangDai)
- [ ] R Programming Basics (@jessica-wyleung)
- [x] How to ask for help (@DanyangDai)
- [x] Project structure (@DanyangDai)
- [x] Importing and exporting data (@DanyangDai)
- [ ] Data wrangling with dplyr & tidyr (@jessica-wyleung)
- [x] Data visualisation (@emitanaka)
- [x] Basic linear regression (@emitanaka)
- [x] R Markdown basics (@DanyangDai)

**Comment by DanyangDai** [comment]
Topics for discussion: 

- [x] What datasets should we use for this short course?

**Comment by emitanaka** [comment]
We should perhaps combine chapter 4 & 5 together @DanyangDai ? Does that look reasonable to you?
