### ISSUE TITLE
Possible incorrect answer in Chapter 7 Section 4

### ISSUE THREAD

**Issue by dwu0042** [numbats/learnr#23]
There seems to be a consistency issue between the result and the comment in the question feedback of 7.4 (MV regression).

See below screenshots

![image](https://user-images.githubusercontent.com/127822470/225508572-4a7590f7-aa22-4f86-99d4-4d4dcc548c3c.png)
![image](https://user-images.githubusercontent.com/127822470/225508603-9d50b5da-81b9-474b-98c8-3bab09da7cda.png)

**Comment by emitanaka** [comment]
Thanks! It should be now corrected.
