### ISSUE TITLE
Outsourcing of video intro sequence

### ISSUE THREAD

**Issue by emitanaka** [numbats/learnr#3]
@mitchelloharawild , did you want to find someone that can do this and get a quote for it?

**Comment by mitchelloharawild** [comment]
I'm currently testing someone out making an intro for fable, if they're good I can use them again for this.

**Comment by mitchelloharawild** [comment]
I have submitted this storyboard for animation. The cost is AUD$53.84.
[storyboard.pdf](https://github.com/numbats/learnr/files/8113097/storyboard.pdf)

**Comment by emitanaka** [comment]
@robjhyndman do you approve this to go ahead?

**Comment by robjhyndman** [comment]
Sure, no problem

**Comment by mitchelloharawild** [comment]
Final intro video

https://user-images.githubusercontent.com/16127127/155642750-57f2742f-f9bd-4a9c-9dd9-25eb21d250e9.mp4
