### ISSUE TITLE
Persistent code environments

### ISSUE THREAD

**Issue by mitchelloharawild** [numbats/learnr#4]

**Comment by mitchelloharawild** [comment]
Resolved in 58cc271dba97a651315f7c32bc17114427099ba6

**Comment by emitanaka** [comment]
Doesn't look resolved
![Screen Shot 2022-02-23 at 7 11 13 pm](https://user-images.githubusercontent.com/7620319/155281825-5b27eb4a-42f4-4b2b-a96c-6596eba6e696.png)

**Comment by emitanaka** [comment]
Screenshot of previous exercise:
 
![Screen Shot 2022-02-23 at 7 12 21 pm](https://user-images.githubusercontent.com/7620319/155281961-5af7d66e-e949-47f6-9293-68563fa7e3c7.png)

**Comment by mitchelloharawild** [comment]
Hmm, seems like we have persistence within a single cell, but not across cells as I was expecting from the juniper docs.

**Comment by mitchelloharawild** [comment]
Related issue: https://github.com/ines/course-starter-python/issues/24

**Comment by mitchelloharawild** [comment]
I now know the inner workings of juniper enough to make my own version if desired :laughing: 
I think I've made it work now, before spinning up a new kernel in the binder env, it will check if any exist already and connect to those instead (which still have the existing environment).

**Comment by emitanaka** [comment]
Ok checked. It's working. And no need to remake your own version! Let's stick with the chimera that we have now so long as it's working and let the next team (or future us) worry about any changes!
