### ISSUE TITLE
Review ch6,7

### ISSUE THREAD

**Issue by jessica-wyleung** [numbats/learnr#7]
@emitanaka  I did the review looking at the version here: https://learnr.numbat.space/chapter6

- `<br>` is showing here.
<img width="833" alt="Screen Shot 2022-02-21 at 10 32 33 am" src="https://user-images.githubusercontent.com/54132201/154869276-51e8de1b-8ddb-44e0-841c-daa52fbb4f9a.png">
- All the graphs are not showing up in slides at (1) (3) (4) (6) (8) (10) (13)
<img width="1722" alt="Screen Shot 2022-02-21 at 10 34 19 am" src="https://user-images.githubusercontent.com/54132201/154869333-d5c1a209-c6a6-47fa-9679-1df7f17292b0.png">
- The page `Summary of R graphics` at (1) seems to be blank.
- (12) Customise the look with themes in ggplot2 is blank
- Perhaps we should be consistent with the title about with or without full stop? ( (9) and (11) has full stops. )

Chapter 7: https://learnr.numbat.space/chapter7

Latex and some html raw code are showing.
I can't see the bottom line of slides (1) even when I am using full screen.
(2) (4) (6) are blank at the moment.

**Comment by emitanaka** [comment]
I suspect GitHub pages is pointing to an old version when we switched DNS. @mitchelloharawild can you check?

**Comment by emitanaka** [comment]
@jessica-wyleung I think for slide 1 for data vis, you might be looking at the cache? You might need to refresh or clear cache? The one I'm looking at shows the picture in that one but some other sections are not showing pictures even though I see it in the static folder. 

Regarding latex not showing, I think Mitch is still yet to do #5 , so I'm assuming it will be sorted when that is done

**Comment by mitchelloharawild** [comment]
Presumably a caching issue. Clear your stored website content for learnr.numbat.space.

**Comment by mitchelloharawild** [comment]
Math should now be fixed too. Could you check the that the technical issues mentioned above are now fixed?

**Comment by emitanaka** [comment]
All good with latex issue and all other issues mentioned are resolved.
